version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    command: mongod --noauth
    networks:
      - my-network

  nodejs:
    image: micro:latest
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - my-network

  nodejs-app2:
    image: apk:latest
    ports:
      - "3000:3000"
    depends_on:
      - nodejs
      - mongodb
    networks:
      - my-network

networks:
  my-network: